version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis_server
    expose:
      - 6379
    restart: always

  api:
    build: .
    container_name: kobold_keeper_api
    command: /usr/local/bin/start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  worker:
    build: .
    container_name: kobold_keeper_worker
    command: celery -A kobold_keeper worker -l info
    volumes:
      - .:/app
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

volumes:
  postgres_data:
